### ISSUE TITLE
The Google Drive integration was blocked by Google!

### ISSUE THREAD

**Issue by FieryMewtwo** [BinBashBanana/webretro#10]
Just a heads-up.

**Comment by BinBashBanana** [comment]
I'm aware of this, for now, you can press "Advanced" and authorize that way. This will be fixed when I verify this app with google, which is a complicated and time-consuming process, so it is not top priority.

**Comment by FieryMewtwo** [comment]
Oh, okay.

**Comment by BinBashBanana** [comment]
I'm going to keep this issue open until it's fixed

**Comment by BinBashBanana** [comment]
Well, it looks like I'll need to verify a domain, which involves setting a DNS record on binbashbanana.github.io (I can't do that because GitHub owns the domain). Regular site verification does not work for this. So for now, continue to just press Advanced; I have no intentions to purchase a domain anytime soon.
