### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by WhenIsItBig** [BinBashBanana/webretro#47]
i've been a great fan of this emulator but theres one thing that makes me want to kill myself
i can't play pokemon nds games because they're too laggy
can you add bigger file support
the game still works but at like 10 frames
thanks
pokemon is life

**Comment by ethanaobrien** [comment]
> i can't play pokemon nds games because they're too laggy

The reason for this will be the cpu power of your device. Lower end devices may not have the capability to run newer emulators in the web browser. I have a friend who plays ds games in the browser and they run at 60fps on his machine so it's not really something that can be fixed

> can you add bigger file support

The only size limit for the files are limits not because of anything we can do, but limits of the browser itself, and ds roms are not likely to reach this limit


Also @BinBashBanana I hope you're ok with me trying to help people like this, if not let me know and I'll stop.

**Comment by BinBashBanana** [comment]
@ethanaobrien yeah it's ok

@WhenIsItBig file size is not at all related to emulator speed, however when I finish the GLES 3.0 support on melonDS it should be faster.
