### ISSUE TITLE
PSP core

### ISSUE THREAD

**Issue by sDetective** [BinBashBanana/webretro#48]
Could it be possible to have the PlayStation portable core in the future?

**Comment by ethanaobrien** [comment]
See https://github.com/BinBashBanana/webretro/issues/6#issuecomment-1246073449 -- yes this may be possible. I got some of it done then asked for help because I'm less experienced in that area

Just note - if you can barely run PlayStation games, the chances of being able to run psp games are incredibly small. The roms are much bigger

**Comment by BinBashBanana** [comment]
Also see #28
