### ISSUE TITLE
16:9 internal aspect ratio?

### ISSUE THREAD

**Issue by obscurerev** [BinBashBanana/webretro#7]
the emulator itself is stuck in 4:3. like the actual retroarch thing itself. is there a way to fix this?

**Comment by BinBashBanana** [comment]
I can change the aspect ratio before I compile it, but I don't because all of the cores' aspect ratios are 4:3 (or very, very close to 4:3). Eventually, I am going to add support for mobile/touch devices, and depending on the chosen controller layout, the display may have to be in 4:3 in order to fit on the screen.

**Comment by BinBashBanana** [comment]
@obscurerev fixed in v6.5.
